### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by oatmealm** [kljohann/mpv.el#17]
Is there an example of how to configure keybindings for the various options?

Thanks a lot for a very useful package.

**Comment by kljohann** [comment]
Thanks, maybe that's something to add to the [wiki](https://github.com/kljohann/mpv.el/wiki). I did not include any keybindings with the package itself, since they'll probably depend on the use case or personal preferences.

If you want some examples, there is https://github.com/yuchen-lea/org-media-note (which I did not yet try myself) for note taking, and the following minor mode from my personal config (but I don't remember how it got there… :slightly_smiling_face:):

```
(define-minor-mode mpv-mode
  "Provide key bindigs for controlling mpv.  See `mpv-play'.

The following commands are available:

\\{mpv-mode-map}"
  nil
  (if (char-displayable-p ?▶) " ▶" " mpv")
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "f")       'mpv-play)
    (define-key map (kbd "SPC")     'mpv-pause)
    (define-key map (kbd "<right>") 'mpv-seek-forward)
    (define-key map (kbd "<left>")  'mpv-seek-backward)
    (define-key map (kbd "<up>")    'mpv-speed-increase)
    (define-key map (kbd "<down>")  'mpv-speed-decrease)
    (define-key map (kbd "k")       'mpv-kill)
    (define-key map (kbd "q")       'mpv-kill)
    (define-key map (kbd "i")       'mpv-insert-playback-position)
    (define-key map (kbd "RET")     'mpv-seek-to-position-at-point)
    `(("\C-cm" . ,map)))
  :global t
  :group 'mpv)
```

**Comment by oatmealm** [comment]
Thanks. Much appreciated. Also the tip about org-media-note. Will have a look.
